2024-03-18 23:26:41,300 INFO    StreamThr :80124 [internal.py:wandb_internal():86] W&B internal server running at pid: 80124, started at: 2024-03-18 23:26:41.299805
2024-03-18 23:26:41,302 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status
2024-03-18 23:26:41,315 INFO    WriterThread:80124 [datastore.py:open_for_write():87] open: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/run-ujohoe53.wandb
2024-03-18 23:26:41,316 DEBUG   SenderThread:80124 [sender.py:send():378] send: header
2024-03-18 23:26:41,335 DEBUG   SenderThread:80124 [sender.py:send():378] send: run
2024-03-18 23:26:42,028 INFO    SenderThread:80124 [dir_watcher.py:__init__():211] watching files in: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files
2024-03-18 23:26:42,028 INFO    SenderThread:80124 [sender.py:_start_run_threads():1099] run started: ujohoe53 with start time 1710784601.300935
2024-03-18 23:26:42,045 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: check_version
2024-03-18 23:26:42,045 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: check_version
2024-03-18 23:26:42,122 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: run_start
2024-03-18 23:26:42,129 DEBUG   HandlerThread:80124 [system_info.py:__init__():26] System info init
2024-03-18 23:26:42,129 DEBUG   HandlerThread:80124 [system_info.py:__init__():41] System info init done
2024-03-18 23:26:42,129 INFO    HandlerThread:80124 [system_monitor.py:start():194] Starting system monitor
2024-03-18 23:26:42,130 INFO    SystemMonitor:80124 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-18 23:26:42,130 INFO    HandlerThread:80124 [system_monitor.py:probe():214] Collecting system info
2024-03-18 23:26:42,132 INFO    SystemMonitor:80124 [interfaces.py:start():190] Started cpu monitoring
2024-03-18 23:26:42,132 DEBUG   HandlerThread:80124 [system_info.py:probe():150] Probing system
2024-03-18 23:26:42,132 INFO    SystemMonitor:80124 [interfaces.py:start():190] Started disk monitoring
2024-03-18 23:26:42,137 INFO    SystemMonitor:80124 [interfaces.py:start():190] Started gpuapple monitoring
2024-03-18 23:26:42,139 INFO    SystemMonitor:80124 [interfaces.py:start():190] Started memory monitoring
2024-03-18 23:26:42,142 INFO    SystemMonitor:80124 [interfaces.py:start():190] Started network monitoring
2024-03-18 23:26:42,144 DEBUG   HandlerThread:80124 [system_info.py:_probe_git():135] Probing git
2024-03-18 23:26:42,162 DEBUG   HandlerThread:80124 [system_info.py:_probe_git():143] Probing git done
2024-03-18 23:26:42,162 DEBUG   HandlerThread:80124 [system_info.py:probe():198] Probing system done
2024-03-18 23:26:42,162 DEBUG   HandlerThread:80124 [system_monitor.py:probe():223] {'os': 'macOS-12.5.1-arm64-arm-64bit', 'python': '3.9.6', 'heartbeatAt': '2024-03-18T17:56:42.132520', 'startedAt': '2024-03-18T17:56:41.286767', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '/Users/omkar/deep_learning/CS21D202_DL_1/train.py', 'codePathLocal': 'train.py', 'codePath': 'train.py', 'git': {'remote': 'git@github.com:omkar-cs21s042/CS21D202_DL_1.git', 'commit': 'c9b68e3303880156c9a946d3345518cba8777cf7'}, 'email': 'cs21s042@smail.iitm.ac.in', 'root': '/Users/omkar/deep_learning/CS21D202_DL_1', 'host': 'Omkars-MacBook-Air.local', 'username': 'omkar', 'executable': '/Library/Developer/CommandLineTools/usr/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 3204, 'min': 600, 'max': 3204}, 'cpu_freq_per_core': [{'current': 3204, 'min': 600, 'max': 3204}], 'disk': {'/': {'total': 228.27386474609375, 'used': 14.368236541748047}}, 'gpuapple': {'type': 'arm', 'vendor': 'Apple'}, 'memory': {'total': 8.0}}
2024-03-18 23:26:42,162 INFO    HandlerThread:80124 [system_monitor.py:probe():224] Finished collecting system info
2024-03-18 23:26:42,162 INFO    HandlerThread:80124 [system_monitor.py:probe():227] Publishing system info
2024-03-18 23:26:42,163 INFO    HandlerThread:80124 [system_monitor.py:probe():229] Finished publishing system info
2024-03-18 23:26:42,170 DEBUG   SenderThread:80124 [sender.py:send():378] send: files
2024-03-18 23:26:42,170 INFO    SenderThread:80124 [sender.py:_save_file():1365] saving file wandb-metadata.json with policy now
2024-03-18 23:26:42,216 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: python_packages
2024-03-18 23:26:42,216 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: python_packages
2024-03-18 23:26:42,217 DEBUG   SenderThread:80124 [sender.py:send():378] send: telemetry
2024-03-18 23:26:42,217 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 23:26:42,217 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: stop_status
2024-03-18 23:26:42,218 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 23:26:42,614 DEBUG   SenderThread:80124 [sender.py:send():378] send: telemetry
2024-03-18 23:26:42,614 DEBUG   SenderThread:80124 [sender.py:send():378] send: run
2024-03-18 23:26:42,938 INFO    SenderThread:80124 [sender.py:send_run():973] updated run: ujohoe53
2024-03-18 23:26:43,033 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/config.yaml
2024-03-18 23:26:43,033 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/wandb-metadata.json
2024-03-18 23:26:43,033 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/requirements.txt
2024-03-18 23:26:43,552 INFO    wandb-upload_0:80124 [upload_job.py:push():131] Uploaded file /var/folders/_w/4w4x7prn23l61klhvr58ykvh0000gn/T/tmp7rx4upcawandb/ww3mllen-wandb-metadata.json
2024-03-18 23:26:46,959 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:26:51,984 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:26:57,010 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:26:57,221 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 23:26:57,222 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 23:26:57,222 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: stop_status
2024-03-18 23:26:57,615 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: partial_history
2024-03-18 23:26:57,992 DEBUG   SenderThread:80124 [sender.py:send():378] send: history
2024-03-18 23:26:57,992 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: summary_record
2024-03-18 23:26:57,993 INFO    SenderThread:80124 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-18 23:26:58,109 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/wandb-summary.json
2024-03-18 23:26:58,109 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_created():271] file/dir created: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/output.log
2024-03-18 23:27:00,119 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/output.log
2024-03-18 23:27:02,013 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:07,038 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:12,066 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:12,226 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-18 23:27:12,226 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: stop_status
2024-03-18 23:27:12,339 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: stop_status
2024-03-18 23:27:13,057 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: partial_history
2024-03-18 23:27:13,057 DEBUG   SenderThread:80124 [sender.py:send():378] send: history
2024-03-18 23:27:13,057 DEBUG   SenderThread:80124 [sender.py:send_request():405] send_request: summary_record
2024-03-18 23:27:13,058 INFO    SenderThread:80124 [sender.py:_save_file():1365] saving file wandb-summary.json with policy end
2024-03-18 23:27:13,185 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/wandb-summary.json
2024-03-18 23:27:13,185 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/config.yaml
2024-03-18 23:27:14,190 INFO    Thread-12 :80124 [dir_watcher.py:_on_file_modified():288] file/dir modified: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/files/output.log
2024-03-18 23:27:18,082 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:23,108 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:28,128 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:33,147 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:38,168 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:42,146 DEBUG   SystemMonitor:80124 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-18 23:27:42,148 DEBUG   SenderThread:80124 [sender.py:send():378] send: telemetry
2024-03-18 23:27:42,148 DEBUG   SenderThread:80124 [sender.py:send():378] send: stats
2024-03-18 23:27:42,432 ERROR   FileStreamThread:80124 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/omkard/myprojectname/ujohoe53/file_stream
NoneType: None
2024-03-18 23:27:44,168 DEBUG   HandlerThread:80124 [handler.py:handle_request():146] handle_request: status_report
2024-03-18 23:27:44,481 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:27:44,482 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:27:45,918 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:27:45,919 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:27:48,271 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:27:48,272 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:27:48,272 INFO    SenderThread:80124 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Library/Python/3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-03-18 23:27:53,395 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:27:53,396 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:28:03,231 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:28:03,231 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:28:23,293 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:28:23,295 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:29:02,611 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:29:02,612 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:30:16,854 ERROR   SenderThread:80124 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-18 23:30:16,856 ERROR   SenderThread:80124 [internal_api.py:execute():374] {"errors":[{"message":"run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-18 23:30:17,201 INFO    HandlerThread:80124 [handler.py:finish():869] shutting down handler
2024-03-18 23:30:17,202 INFO    HandlerThread:80124 [system_monitor.py:finish():203] Stopping system monitor
2024-03-18 23:30:17,202 INFO    WriterThread:80124 [datastore.py:close():296] close: /Users/omkar/deep_learning/CS21D202_DL_1/wandb/run-20240318_232641-ujohoe53/run-ujohoe53.wandb
2024-03-18 23:30:17,203 DEBUG   SystemMonitor:80124 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-18 23:30:17,203 INFO    HandlerThread:80124 [interfaces.py:finish():202] Joined cpu monitor
2024-03-18 23:30:17,204 DEBUG   SystemMonitor:80124 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-18 23:30:17,204 INFO    HandlerThread:80124 [interfaces.py:finish():202] Joined disk monitor
2024-03-18 23:30:17,206 INFO    HandlerThread:80124 [interfaces.py:finish():202] Joined gpuapple monitor
2024-03-18 23:30:17,207 INFO    HandlerThread:80124 [interfaces.py:finish():202] Joined memory monitor
2024-03-18 23:30:17,207 INFO    HandlerThread:80124 [interfaces.py:finish():202] Joined network monitor
2024-03-18 23:30:17,256 ERROR   StreamThr :80124 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_api.py", line 2216, in upsert_run
    response = self.gql(
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_api.py", line 341, in gql
    ret = self._retry_gql(
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/Library/Python/3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/sender.py", line 536, in debounce
    self._maybe_update_config(always=final)
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/sender.py", line 513, in _maybe_update_config
    self._debounce_config()
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/sdk/internal/sender.py", line 542, in _debounce_config
    self._api.upsert_run(
  File "/Users/omkar/Library/Python/3.9/lib/python/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run omkard/myprojectname/ujohoe53 was previously created and deleted; try a new run name (Error 409: Conflict)
